name: Verificación del proyecto # nombre del flujo de trabajo

on: 
  push: 
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs: # definicion del trabajo
  build: # nombre del trabajo
    runs-on: ubuntu-latest # entorno de ejecución

    steps: # Pasos del trabajo
      - name: Clonar el repositorio 
        uses: actions/checkout@v3 # Acción para clonar el repositorio

      - name: Configurar Python 
        uses: actions/setup-python@v4 # Acción para configurar Python
        with:
          python-version: '3.10' # versión de Python

      - name: Instalar dependencias # instala las dependencias necesarias
        run: | 
          python -m pip install --upgrade pip 
          pip install pandas 

      - name: Verificar el script # verifica que el script se ejecute sin errores
        run: python -m py_compile preprocesamiento.py # compila el script para verificar errores de sintaxis
